### ISSUE TITLE
Multiplayer Support

### ISSUE THREAD

**Issue by ywmaa** [OctoD/godot-gameplay-systems#38]
**Is your feature request related to a problem? Please describe.**
Multiplayer Support Out Of The Box

**Describe the solution you'd like**
I am going to add this awesome system (thank you for it) to my multiplayer game.
so I am going to add multiplayer system to it.
I am offering to do a PR after I finish the integeration in my game.

in my game I always pack my Nodes that needs to be synced in a Seperate Scene, and add Multiplayer Sync to it, and choose properties that needs to be synced.

or we can use RPC beside its code (I would like to avoid that to not bloat the code for non multiplayer users)

**Describe alternatives you've considered**
Maybe I just document my way of getting it for multiplayer and add it to the WIKI, instead of having it built-in.

**Additional context**
N/A

**Comment by OctoD** [comment]
Adding multiplayer on a similar system is something I am already thinking to add. 

Unfortunately it's hard to make a general purpose networking code because it always depends on the scope of the project (a turn based rpg can be done with tcp alone, but a real-time competitive looter shooter or arpg like borderlands and Diablo require other approaches). 

I am curious about what you want to achieve though.
