### ISSUE TITLE
🐛 [bug] The attribute of "Gameplayattributemap"

### ISSUE THREAD

**Issue by Abab-bk** [OctoD/godot-gameplay-systems#40]
**Describe the bug**
I read the document and it said:

This node accepts an AttributeTable resource as value. This resource specifies which attributes the entity has.
Next is:

Once specified a table, the inspector will show you these attributes, where you can set a:

minimum value: which usually is zero
maximum value: if you set it to zero, there will be not a maximum
current value: the starting value for the entity

But in fact, I found that "Attributes" has "Minimum Value" entries. Is this a document error?

Godot4.1.1 Stable.

**Comment by OctoD** [comment]
May I ask what exactly the issue is about? 

An attribute has 
- a `minimum` value (which forces the `current` value cannot be lower to it, so if we set it to `0`, and try to apply an effect which lowers it by `-10`, the current value will never be lower than `0`)
- a `maximum` value (which acts as a hard cap for the attribute (except if you apply buffs)
- a `current` value (which, while editing, is intended as the initial value)

Surely the docs need some rework, they are badly written.

Thank you!

**Comment by Abab-bk** [comment]
No problem now, this should be a Godot bug, before I restart the Godot, "attributes" of Gameplayattributemap node are an array.

**Comment by OctoD** [comment]
Ah yes, it could be an issue with the inspector plugins. I will investigate anyway, and add a note about reloading the project on the main readme. 
Thank you!
